# Generated by Django 2.1.2 on 2018-10-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='comments_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
